[project]
name = "pointcloud-processing-sample"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.1",
    "open3d>=0.19.0",
    "pdal>=3.4.5",
    "rasterio>=1.4.3",
]
